"""Generate jaato-eval tasks for a backtest matrix: tickers × a date grid × repeats.

A backtest is a jaato-eval sweep whose arms are runs of this driver
(``harness.kind: driver``, jaato #1110), one task per ``(ticker, date)``
cell, graded by :mod:`ta_cascade.score`.  jaato-eval owns everything
matrix-shaped — repeats, arms across profile sets, per-arm scratch
workspaces, resume, concurrency, the per-arm ceiling, the report — so this
module writes manifests and nothing else.

Layout, under ``<repo>/backtests/<name>/``::

    fixture/                 an empty tree: the arm workspace starts with
                             nothing, and the engine writes its .env
    tasks/<TICKER>-<DATE>/task.yaml

and the run is::

    jaato-eval run backtests/<name>/tasks --profile-set openrouter_sonnet \\
        --socket /tmp/jaato.sock --out backtests/<name>/results.jsonl \\
        --workspaces /tmp/<name>-ws --arm-timeout 1200 --resume

Three facts shape the manifests:

* ``config_root`` points at THIS repository's ``.jaato/``, outside the arm
  workspace, so every arm resolves the same profiles, personas, schemas and
  gates; the driver receives it through the contract.
* No ``budget:`` block.  Every stage profile here carries its own
  ``budget_control``, and a session with its own ceiling is on its own books
  and does not draw on a task pool — the framework's rule.  Each arm is then
  given a cid of its own, which also makes the engine's attribution exact.
* ``--no-memory``.  Every arm is a fresh workspace, so the decision log's
  walk-forward loop (lessons carried from resolved decisions into later
  runs) cannot cross arms; a backtest with memory needs a shared log
  outside the workspace and is not offered here yet.

The default analyst set is ``market`` alone: the news and social sources
serve recent items only, so on a historical date the other analysts would
see nothing but unavailable-data sentences (docs/gaps.md).
"""
from __future__ import annotations

import datetime as dt
from pathlib import Path
from typing import Iterable, List

from .config import ANALYST_KEYS

TASK_TEMPLATE = """\
# Generated by `python -m ta_cascade backtest-tasks`; one cell of the
# `{name}` backtest.  The arm is a run of this repository's driver
# (harness.kind: driver, jaato #1110), graded against realised returns by
# `python -m ta_cascade.score`, which reads the same two params.
id: backtest/{name}/{ticker}/{date}
description: >
  {ticker} as of {date}: run the pipeline with the {analysts} analyst(s),
  then grade the portfolio manager's rating against the realised
  holding-period return versus the benchmark.

environment:
  fixture: {fixture}
  config_root: {config_root}

input:
  params: {{TICKER: {ticker}, TRADE_DATE: "{date}"}}

harness:
  kind: driver
  run: >-
    "$JAATO_EVAL_PYTHON" -m ta_cascade analyze "$JAATO_EVAL_PARAM_TICKER" "$JAATO_EVAL_PARAM_TRADE_DATE"
    --analysts {analysts} --no-memory --display lines
  profile_set: {profile_set}

# No budget: block on purpose — every stage profile carries its own
# budget_control, and a session with its own ceiling never draws on a pool.

graders:
  - kind: script
    run: '"$JAATO_EVAL_PYTHON" -m ta_cascade.score'

repeats: {repeats}
"""


def date_grid(start: dt.date, end: dt.date, every_days: int) -> List[dt.date]:
    """``start``, then every ``every_days`` calendar days, up to and including ``end``."""
    if every_days < 1:
        raise ValueError("every_days must be at least 1")
    if end < start:
        raise ValueError(f"end {end} is before start {start}")
    out, day = [], start
    while day <= end:
        out.append(day)
        day += dt.timedelta(days=every_days)
    return out


def write_tasks(repo: Path, name: str, tickers: Iterable[str], dates: Iterable[dt.date], *,
                repeats: int = 1, analysts: Iterable[str] = ("market",),
                profile_set: str = "openrouter_sonnet") -> List[Path]:
    """Write ``backtests/<name>/`` under ``repo``; return the manifests written."""
    analysts = [a.strip() for a in analysts]
    unknown = [a for a in analysts if a not in ANALYST_KEYS]
    if unknown:
        raise ValueError(f"unknown analyst(s): {unknown}; choose from {ANALYST_KEYS}")
    if repeats < 1:
        raise ValueError("repeats must be at least 1")
    root = repo / "backtests" / name
    fixture = root / "fixture"
    fixture.mkdir(parents=True, exist_ok=True)
    (fixture / ".gitkeep").touch()
    written: List[Path] = []
    for ticker in (t.strip().upper() for t in tickers):
        for day in dates:
            task_dir = root / "tasks" / f"{ticker}-{day.isoformat()}"
            task_dir.mkdir(parents=True, exist_ok=True)
            manifest = task_dir / "task.yaml"
            manifest.write_text(TASK_TEMPLATE.format(
                name=name, ticker=ticker, date=day.isoformat(),
                analysts=",".join(analysts), repeats=repeats, profile_set=profile_set,
                # Relative to the task directory, as the manifest resolves them.
                fixture="../../fixture", config_root="../../../../.jaato",
            ))
            written.append(manifest)
    return written
